/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.contrasegura;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.ClipboardOwner;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;

import javax.swing.UIManager;

/**
 *
 * @author pedro
 */
public class ContraSegura extends javax.swing.JFrame  implements ClipboardOwner{

    /**
     * Creates new form ContraSegura
     */
    public ContraSegura() {
        setLocationRelativeTo(null);
        initComponents();
        
    }
    
    public void setClipboard(String texto){
    
        StringSelection txt = new StringSelection(texto);
        Toolkit.getDefaultToolkit().getSystemClipboard().setContents(txt, this);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        lbl_contraseña = new javax.swing.JLabel();
        txt_contra = new javax.swing.JTextField();
        btn_mejorar = new javax.swing.JButton();
        txt_contramejorada = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btn_copiar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        btn_cerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_contraseña.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_contraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_contraseña.setText("Contraseña");

        txt_contra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_contra.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btn_mejorar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_mejorar.setText("MEJORAR");
        btn_mejorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mejorarActionPerformed(evt);
            }
        });

        txt_contramejorada.setEditable(false);
        txt_contramejorada.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_contramejorada.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btn_copiar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_copiar.setText("COPIAR");
        btn_copiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_copiarActionPerformed(evt);
            }
        });

        btn_limpiar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_limpiar.setText("LIMPIAR");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        btn_cerrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_cerrar.setText("CERRAR");
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_contra)
                    .addComponent(lbl_contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_mejorar, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_copiar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_contramejorada, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_mejorar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_contramejorada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_copiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_limpiar)
                    .addComponent(btn_cerrar))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mejorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mejorarActionPerformed
        // TODO add your handling code here:
        
        String contraseña = null;
        contraseña= txt_contra.getText();
            // System.out.println(contraseña.charAt(i));
            //letras
            
           //contraseña=contraseña.replaceFirst("", "");
           contraseña=contraseña.replaceAll(" ", "_");
           contraseña=contraseña.replaceAll("A", "@");
           contraseña=contraseña.replaceAll("a", "@");
           contraseña=contraseña.replaceAll("B", "b");
           contraseña=contraseña.replaceAll("b", "B");
           contraseña=contraseña.replaceAll("C", "c");
           contraseña=contraseña.replaceAll("c", "C");
           contraseña=contraseña.replaceAll("D", "d"); 
           contraseña=contraseña.replaceAll("d", "D");
           contraseña=contraseña.replaceAll("E", "3");
           contraseña=contraseña.replaceAll("e", "3");
           contraseña=contraseña.replaceAll("F", "f");
           contraseña=contraseña.replaceAll("f", "F");
           contraseña=contraseña.replaceAll("G", "g"); 
           contraseña=contraseña.replaceAll("g", "G");
           contraseña=contraseña.replaceAll("H", "#");
           contraseña=contraseña.replaceAll("H", "#");
           contraseña=contraseña.replaceAll("I", "!");
           contraseña=contraseña.replaceAll("i", "!");
           contraseña=contraseña.replaceAll("J", "¿"); 
           contraseña=contraseña.replaceAll("j", "¿");
           contraseña=contraseña.replaceAll("K", "k");
           contraseña=contraseña.replaceAll("k", "K");
           contraseña=contraseña.replaceAll("L", "1");
           contraseña=contraseña.replaceAll("l", "1");
           contraseña=contraseña.replaceAll("M", "m"); 
           contraseña=contraseña.replaceAll("m", "M");
           contraseña=contraseña.replaceAll("N", "n");
           contraseña=contraseña.replaceAll("n", "N");
           contraseña=contraseña.replaceAll("Ñ", "ñ");
           contraseña=contraseña.replaceAll("ñ", "Ñ");
           contraseña=contraseña.replaceAll("O", "0"); 
           contraseña=contraseña.replaceAll("o", "0");
           contraseña=contraseña.replaceAll("P", "p"); 
           contraseña=contraseña.replaceAll("p", "P");
           contraseña=contraseña.replaceAll("Q", "q");
           contraseña=contraseña.replaceAll("q", "Q");
           contraseña=contraseña.replaceAll("R", "4");
           contraseña=contraseña.replaceAll("r", "4");
           contraseña=contraseña.replaceAll("S", "%"); 
           contraseña=contraseña.replaceAll("s", "%");
           contraseña=contraseña.replaceAll("T", "t");
           contraseña=contraseña.replaceAll("t", "T");
           contraseña=contraseña.replaceAll("U", "u");
           contraseña=contraseña.replaceAll("u", "U");
           contraseña=contraseña.replaceAll("V", "v"); 
           contraseña=contraseña.replaceAll("v", "V");
           contraseña=contraseña.replaceAll("W", "w"); 
           contraseña=contraseña.replaceAll("w", "W");
           contraseña=contraseña.replaceAll("X", "x");
           contraseña=contraseña.replaceAll("x", "X");
           contraseña=contraseña.replaceAll("Y", "&");
           contraseña=contraseña.replaceAll("y", "&");
           contraseña=contraseña.replaceAll("Z", "2"); 
           contraseña=contraseña.replaceAll("z", "2");
           //numeros
           
          // contraseña=contraseña.replaceAll("1", "1");
           contraseña=contraseña.replaceAll("2", "Z");
          // contraseña=contraseña.replaceAll("3", "3");
          // contraseña=contraseña.replaceAll("4", "4");
          // contraseña=contraseña.replaceAll("5", "5"); 
          // contraseña=contraseña.replaceAll("6", "6");
          // contraseña=contraseña.replaceAll("7", "7"); 
          // contraseña=contraseña.replaceAll("8", "8");
          // contraseña=contraseña.replaceAll("9", "9");
          // contraseña=contraseña.replaceAll("0", "#");
           
           //simbolos
        //System.out.println((String)contraseña);
        txt_contramejorada.setText(contraseña);
        txt_contramejorada.enable(false);
        
        
    }//GEN-LAST:event_btn_mejorarActionPerformed

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        // TODO add your handling code here:
        txt_contra.setText("");
        txt_contramejorada.setText("");
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_copiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_copiarActionPerformed
        // TODO add your handling code here:
        setClipboard(txt_contramejorada.getText());
    }//GEN-LAST:event_btn_copiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContraSegura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContraSegura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContraSegura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContraSegura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                 try {
                    UIManager.setLookAndFeel(new FlatLightLaf());
                } catch (Exception ex) {
                    System.err.println("Failed to initialize LaF");
                }
                new ContraSegura().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_copiar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_mejorar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_contraseña;
    private javax.swing.JTextField txt_contra;
    private javax.swing.JTextField txt_contramejorada;
    // End of variables declaration//GEN-END:variables

    @Override
    public void lostOwnership(Clipboard clipboard, Transferable contents) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
